<?php
use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_form_FORM_ID_alter().
 */
function password_change_enforcer_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $uid = $form_state->getFormObject()->getEntity()->id();
  if ($uid == \Drupal::currentUser()->id() && isset($_SESSION["pass_reset_$uid"])) {
    $form['account']['pass']['#required'] = TRUE;
  }
}
